  services:
    app:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      environment:
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      depends_on:
        - db
      networks: [appnet]

    web:
      image: nginx:1.27-alpine
      depends_on:
        - app
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html:delegated
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      networks: [appnet]

    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password --sql-mode=NO_ENGINE_SUBSTITUTION
      environment:
        MYSQL_DATABASE: car_parts
        MYSQL_USER: app
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "33060:3306"
      volumes:
        - db-data:/var/lib/mysql
      networks: [appnet]

    node:
      image: node:22-alpine
      working_dir: /var/www/html
      command: sh -c "npm install && npm run dev -- --host"
      ports:
        - "5173:5173"
      volumes:
        - ./:/var/www/html
      networks: [appnet]

    composer:
      image: composer:2
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
      entrypoint: ["composer"]
      networks: [appnet]

  volumes:
    db-data:

  networks:
    appnet:
